ignores:
  - '@commitlint/*'
  - '@repobuddy/jest'
  - '@size-limit/*'
  - '@types/*'
  - '@typescript-eslint/parser'
  - jest-*
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - ts-jest
