name: nodejs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    uses: unional/.github/.github/workflows/typescript-build.yml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      codacy-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  test:
    uses: unional/.github/.github/workflows/typescript-test.yml@main
    needs: build
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    steps:
      - uses: actions/checkout@v1
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache yarn global cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: download lib folder
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: download libm folder
        uses: actions/download-artifact@v1
        with:
          name: libm
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
